/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("employeesObjectPageObjectPage journey");

        opaTest("Navigate to employeesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThedepartmentList.onFilterBar().iExecuteSearch();

            Then.onThedepartmentList.onTable().iCheckRows();
            When.onThedepartmentList.onTable().iPressRow(0);

            Then.onThedepartmentObjectPage.iSeeThisPage();
            Then.onThedepartmentObjectPage.onTable({ property: "eMPLOYEES" }).iCheckRows();
            When.onThedepartmentObjectPage.onTable({ property: "eMPLOYEES" }).iPressRow(0);

            Then.onTheemployeesObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheemployeesObjectPage.iCheckNumberOfSections(2);
            When.onTheemployeesObjectPage.iPressSectionIconTabFilterButton("GeneratedFacet1");
            Then.onTheemployeesObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheemployeesObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "NAME" });
            Then.onTheemployeesObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DOB" });
            Then.onTheemployeesObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ADDRESS" });
            Then.onTheemployeesObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PHONENO" });
            Then.onTheemployeesObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "EMAIL" });
            When.onTheemployeesObjectPage.iPressSectionIconTabFilterButton("AdminInformation");
            Then.onTheemployeesObjectPage.iCheckSection({ section: "AdminInformation" });
            Then.onTheemployeesObjectPage.onForm({ section: "AdminInformation" }).iCheckField({ property: "createdBy" });
            Then.onTheemployeesObjectPage.onForm({ section: "AdminInformation" }).iCheckField({ property: "createdAt" });
            Then.onTheemployeesObjectPage.onForm({ section: "AdminInformation" }).iCheckField({ property: "modifiedBy" });
            Then.onTheemployeesObjectPage.onForm({ section: "AdminInformation" }).iCheckField({ property: "modifiedAt" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});